steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'Clone the repository'
  args: ['clone', 'https://github.com/giovannidemaria/MyK8sInfrastructure_terraform.git',  './myrepo']
- id: 'files'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      ls
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
        cd ./myrepo/code
        terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd ./myrepo/code
      terraform plan -out=tfplan
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd ./myrepo/code
      terraform apply tfplan
# [END tf-apply]
