steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=code/ init -upgrade "]
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=code/ plan  -out=plan.out"]    
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=code/ apply plan.out"]  
