steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=code/ init -upgrade "]
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=code/ plan"]    
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=code/ apply"]    
  #- id: 'tf destroy plan'
  #  name: 'hashicorp/terraform:1.0.0'
  #  entrypoint: sh
  #  args: ["-c","terraform -chdir=GCP/create-ha-vpn-comm apply plan.out"]    
