steps:
  # Clona la repository contenente il codice di Terraform
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone the repository'
    args: ['clone', 'https://github.com/giovannidemaria/MyK8sInfrastructure_terraform.git',  './myrepo']
  # Inizializza il progetto Terraform
  - name: 'hashicorp/terraform:1.0.0'
    id: 'Initialize the Terraform project'
    entrypoint: sh
    args: ['-c', 'terraform init', './myrepo/code']
    dir: '.'
  # Genera il piano di esecuzione per la creazione o la modifica delle risorse di infrastruttura
  - name: 'hashicorp/terraform:1.0.0'
    id: 'Generate the Terraform plan'
    entrypoint: sh
    args: ['-c', 'terraform plan -out=tfplan', './myrepo/code']
    dir: '.'
  # Applica il piano di esecuzione generato nel passaggio precedente
  - name: 'hashicorp/terraform:1.0.0'
    id: 'Apply the Terraform plan'
    entrypoint: sh
    args: ['-c', 'terraform apply tfplan', './myrepo/code']
    dir: '.'
